# Generated by Django 5.0.4 on 2024-04-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup_app', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='match',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='match',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
