# Generated by Django 5.0.4 on 2024-05-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup_app', '0012_team_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
