# Generated by Django 5.0.4 on 2024-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup_app', '0013_stadium_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
