# Generated by Django 5.0.4 on 2024-05-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup_app', '0014_match_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.CharField(default='Group Stage', max_length=255),
        ),
    ]
