# Generated by Django 5.0.4 on 2024-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup_app', '0015_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
    ]
