# Generated by Django 5.0.4 on 2024-05-18 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup_app', '0016_match_is_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goals', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('matches_played', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_cup_app.team')),
            ],
        ),
    ]
