# Generated by Django 5.0.4 on 2024-05-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup_app', '0017_scorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
